# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moya-Marshal-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 8.0'
  pod 'Moya-Marshal'

  # Pods for Moya-Marshal-Example

  target 'Moya-Marshal-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Moya-Marshal-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
